rm -rf build
mkdir build
cd build

cmake \
  -DUSE_SYSTEM_TCL=OFF \
  -DUSE_SYSTEM_ZLIB=OFF \
  -DUSE_SYSTEM_DB=OFF \
  -DUSE_SYSTEM_GDBM=OFF \
  -DUSE_SYSTEM_LZMA=OFF \
  -DUSE_SYSTEM_READLINE=OFF \
  -DUSE_SYSTEM_SQLITE3=OFF \
  -DENABLE_SSL=OFF \
  -DENABLE_HASHLIB=OFF \
  -DENABLE_MD5=OFF \
  -DENABLE_SHA=OFF \
  -DENABLE_SHA256=OFF \
  -DENABLE_SHA512=OFF \
  ..

