rmdir /s /q build
mkdir build

cd build
cmake.exe -G "Visual Studio 17 2022" -A x64 ^
 -DUSE_SYSTEM_TCL=OFF ^
 -DUSE_SYSTEM_ZLIB=OFF ^
 -DUSE_SYSTEM_DB=OFF ^
 -DUSE_SYSTEM_GDBM=OFF ^
 -DUSE_SYSTEM_LZMA=OFF ^
 -DUSE_SYSTEM_READLINE=OFF ^
 -DUSE_SYSTEM_SQLITE3=OFF ^
 -DENABLE_SSL=OFF ^
 -DENABLE_HASHLIB=OFF ^
 -DENABLE_MD5=OFF ^
 -DENABLE_SHA=OFF ^
 -DENABLE_SHA256=OFF ^
 -DENABLE_SHA512=OFF ^
 ..

